### ISSUE TITLE
Allow specifing 'artifacts' parameter from a file

### ISSUE THREAD

**Issue by nvgoldin** [lago-project/lago#392]
Currently, ovirtlago has the list of logs to collect in the plugin code. This is problematic as it should be possible to configure such a thing easily from the init file, without touching the code.
The 'artifacts' parameter can be defined in the init file, but it does not allow to include other files, so if you have an hierarchy of logs you'd like to collect you have to redefine them over and over again on each init file.

I suggest to add to the spec file 'artifacts_file' parameter, which is a path to a file, that holds list of files to collect from the VM. All those files would be merged and collected together when ``lago collect`` is called.

Example:
```
> cat base_logs
/var/log/messages
/var/log/httpd/
>cat postgres_logs
/var/log/postgres
>cat vdsm.logs
/var/log/bdsm
```

```
> cat LagoInitFile
postgres-server:
   ...
   artifact_list:
     - base_logs
     - postgres_logs
....
httpd-server:
  ...
  artifact_list:
      - base_logs
      - httpd_logs
```

note: Using PyYAML built-in mechanism for this would have made things simpler, but we also need to support JSON.

**Comment by ifireball** [comment]
I don't really like spreading out this kind of data over many external files, why not dedicate a YAML section for this instead?

Something like:
```
domains:
  foo:
    logsets:
      - linux-system
      - ovirt-hypervisor

logsets:
  linux-system:
    - /var/log/messages*
    - /var/log/secure
  ovirt-hypervisor:
    - /var/log/vdsm/*
```
