### ISSUE TITLE
el6 machines fail to boot

### ISSUE THREAD

**Issue by nvgoldin** [lago-project/lago#504]
It was reported by @danielBelenky  that el6 machines fail to boot, I can replicate it on my env with this simple init file:
```yaml
domains:
  lago-basic-suite-3-6-engine:
    vm-type: ovirt-engine
    memory: 4096
    nics:
      - net: lago-basic-suite-3-6-net-management
    disks:
      - template_name: el6-base
        type: template
        name: root
        dev: vda
        format: qcow2
    metadata:
      ovirt-engine-password: 123


nets:
  lago-basic-suite-3-6-net-management:
    type: nat
    dhcp:
      start: 100
      end: 254
    management: true
    dns_domain_name: lago.local
```

Investigating.
