### ISSUE TITLE
Remove iso disks from exported init file

### ISSUE THREAD

**Issue by gbenhaim** [lago-project/lago#605]
An example of a bad exported init file:

```

domains:
  lago-image-ng-suite-4-1-engine:
    boot_time_sec: 500
    bootstrap: false
    cpu: 4
    disks:
    - build: &id001
      - virt-customize: {no-network: null, ssh-inject: ''}
      dev: vda
      format: qcow2
      name: 03ae8e42-6f17-4e06-95bf-bdc546918aa9
      path: $LAGO_INITFILE_PATH/lago-image-ng-suite-4-1-engine_03ae8e42-6f17-4e06-95bf-bdc546918aa9.qcow2
      template_type: qcow2
      type: template
    - {dev: sda, format: iso, name: cloud-init, path: $LAGO_INITFILE_PATH/seed.iso,
      type: file}
    distro: el7


```
