### ISSUE TITLE
virt-customize builder will not respect the order of the commands

### ISSUE THREAD

**Issue by gbenhaim** [lago-project/lago#708]
```
domains:
  vm01:
    artifacts: [/var/log]
    bootstrap: false
    disks:
    - build:
      - virt-customize:
          ssh-inject: ''
          copy: dummy_file:/root
          touch: [/root/file1, /root/file2]
          selinux-relabel: ''
```

Since the commands are specified as a dict, the order of execution isn't deterministic.
A good solution will be to allow specifying a multiline string that will be passed to the `--commands-from-file ` flag of virt-customize.
